brew 'coreutils'
cask 'java'
brew 'git'
brew 'sqlite'
brew 'mas'
brew 'shellcheck'
brew 'ssh-copy-id'
brew 'wget'
brew 'tree'
brew 'pwsafe'
cask 'google-chrome'
cask 'alfred'
cask 'spectacle'

cask 'emacs'
# tap 'd12frosted/emacs-plus'
# brew 'emacs-plus' , args: [ '--with-cocoa', '--with-gnutls' , '--with-librsvg', '--with-imagemagick', '--with-spacemacs-icon' ]

cask 'skype'
cask 'spotify'
