brew 'coreutils'
brew 'git'
brew 'sqlite'
brew 'mas'
brew 'shellcheck'
brew 'ssh-copy-id'
brew 'wget'
brew 'ack'
brew 'tmux'
brew 'tmate'
brew 'tree'
brew 'pwsafe'
brew 'markdown'
brew 'httpie'
brew 'pandoc'
brew 'aspell', args: ['with-lang-nb', 'with-lang-en']
brew 'mongoose'
brew 'postgresql'

# languages not under anyenv
cask 'java'
brew 'typesafe-activator'
brew 'erlang'
brew 'elixir'
brew 'chicken'
brew 'guile'
cask 'gambit-c'
cask 'petite-chez-scheme'

# autotools
brew 'autoconf'
brew 'automake'
brew 'gettext'
brew 'libtool'
brew 'pkgconfig'
brew 'shtool'
brew 'autogen'
brew 'autoconf-archive'

cask 'mactex'
cask 'iterm2'
cask 'google-chrome'
cask 'alfred'
cask 'spectacle'
cask 'jumpcut'
cask 'emacs'
#cask 'intellij-idea-ce'
cask 'skype'
cask 'spotify'
cask 'prezi'
cask 'dockertoolbox'
